### ISSUE TITLE
Ingresses shouldn't contain paths

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform-helm-charts#229]
Here are a couple of hacks I had to do to make accelerator look like alpha. This is a reminder to myself to apply these somewhere in the set-up.

```
k edit ing cpanel-master-cpanel
# remove the "path: /"
spec:
  rules:
  - host: cpanelapi-master.services.accelerator.data-science.org.uk
    http:
      paths:
      - backend:
          serviceName: cpanel-master-cpanel
          servicePort: 80
        path: /

k edit ing cpfrontend-cpfrontend
# remove the "path: /" and add tls block
  tls:
  - hosts:
    - cpanel-master.services.alpha.mojanalytics.xyz
```
